<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by Flight_s2id_autogen2</name>
   <tag></tag>
   <elementGuidId>ba5701df-ca21-4217-9304-abdc248fa008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#s2id_autogen2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='s2id_autogen2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>943cfd6d-fd8c-4fcc-8e15-8840d8eb1f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b31fc95f-4ebd-4d30-a25e-90be3ee47e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>230f159d-1d60-46ec-99f2-4f70123f6e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d8a5781a-3549-4a13-b94c-054d2c79a60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3149ab07-72d8-48e6-aa38-7e2740a9e21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ec16e49a-c02e-4970-8a10-06928c716433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-input select2-active select2-focused</value>
      <webElementGuid>e984efa9-8973-43d0-9ba8-a18d632e8149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s2id_autogen2</value>
      <webElementGuid>9f766c9c-2b70-4afb-844b-93a69fa37571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4c775dd2-b875-47c1-81f6-33cb5e65605f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s2id_autogen2&quot;)</value>
      <webElementGuid>b3368f37-190b-4512-8259-c6f2d69283c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='s2id_autogen2']</value>
      <webElementGuid>4ee96af0-37d1-44f8-a3b1-5e487b79ca86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s2id_omni_findAirlineMain']/ul/li/input</value>
      <webElementGuid>32c3cbc1-5950-4c41-a038-c189139adf62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/ul/li/input</value>
      <webElementGuid>faf1bf14-59ba-4652-a982-fe94da227cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 's2id_autogen2']</value>
      <webElementGuid>8845c616-e41b-4e7b-8bcc-d506c96c04ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
