<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by Route_origin</name>
   <tag></tag>
   <elementGuidId>70906a8c-cbcb-4730-9bcd-efb8681ae147</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.trackInput.active > input[name=&quot;origin&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='origin'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f6c86ee-c530-4096-9d8e-e2d628a9c7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>3554d8ab-d6f3-4b83-a7a1-06c8f83c56e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trackRouteOrigin</value>
      <webElementGuid>eba66ee4-334f-4d1a-91ef-5fbacebc0474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64a65810-74e5-4f8a-8977-685ecfeb84f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Origin</value>
      <webElementGuid>8de79967-6440-405d-9557-bd7d5432a10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Origin</value>
      <webElementGuid>df4b03f2-cf8c-47d4-a191-6bb5d59eca7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Origin</value>
      <webElementGuid>7f79c24d-68d9-400e-b9b4-5ff2a53c7d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>787db6c6-5c4e-479c-98dd-ebd5d2026532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>25a3c4db-803d-4935-ad8f-40cad3b74fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;findRouteMain&quot;)/div[@class=&quot;flightSearchForm&quot;]/div[@class=&quot;searchOption routeSearch text_align_left&quot;]/form[@class=&quot;active&quot;]/div[@class=&quot;trackInputContainer&quot;]/div[@class=&quot;trackInput active&quot;]/input[@class=&quot;trackRouteOrigin&quot;]</value>
      <webElementGuid>d55f207b-ac3c-457c-9886-1b4c6d9194e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='origin'])[2]</value>
      <webElementGuid>57d97165-4a91-4f22-aa1c-82b58bd5472c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='findRouteMain']/div[2]/div/form/div/div/input</value>
      <webElementGuid>375989f9-3330-4d43-b471-69826e4e4175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div/input</value>
      <webElementGuid>9af4f22e-31c5-4fb1-ab3a-804186b76ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'origin' and @type = 'text' and @placeholder = 'Origin' and @title = 'Origin']</value>
      <webElementGuid>48a2440c-2d8d-4295-a089-d6400ce13c2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
