<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by Route_destination</name>
   <tag></tag>
   <elementGuidId>4e42ff1c-78de-43be-9aa8-ecef40425f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.trackInput.active > input[name=&quot;destination&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='destination'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58c1bb76-8f7b-402a-b354-f2f329809b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>destination</value>
      <webElementGuid>b0b85912-8c9f-4df4-a2f5-299ede31282d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trackRouteDestination</value>
      <webElementGuid>501bf56e-d9c9-4c81-a439-4fd5027952d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da09fed4-2248-4677-b7f9-22d84cad2b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Destination </value>
      <webElementGuid>d5798396-fc32-44a1-9397-11d371aff514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Destination </value>
      <webElementGuid>3fc689a9-cbb2-4b10-865b-d7e9ca082de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Destination </value>
      <webElementGuid>349cbcfc-c69e-49c1-ba22-4bf4a8571a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>237e1e5d-d609-4511-8a94-17fab4e97378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>733dc552-7612-42db-98b1-d45c2a418690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;findRouteMain&quot;)/div[@class=&quot;flightSearchForm&quot;]/div[@class=&quot;searchOption routeSearch text_align_left&quot;]/form[@class=&quot;active&quot;]/div[@class=&quot;trackInputContainer&quot;]/div[@class=&quot;trackInput active&quot;]/input[@class=&quot;trackRouteDestination&quot;]</value>
      <webElementGuid>49b10f48-e582-4773-9d9e-6c0800614d13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='destination'])[2]</value>
      <webElementGuid>039237b5-6c4c-4963-83ee-c5d47b1a4d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='findRouteMain']/div[2]/div/form/div[3]/div/input</value>
      <webElementGuid>a493640a-5d25-490b-9eda-ed7bfb6bc471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[3]/div/input</value>
      <webElementGuid>d86f36e0-a2dd-48be-8f6a-5f49ee72595e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'destination' and @type = 'text' and @placeholder = 'Destination ' and @title = 'Destination ']</value>
      <webElementGuid>d464603d-0c9b-4846-8bf6-67b5fe5db919</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
