<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_IGO74</name>
   <tag></tag>
   <elementGuidId>95ade9e9-b5f8-496e-bcc3-d17fec544ab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flightPageIdent > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainBody']/div/div[2]/div[3]/div/div/div/div[2]/div/div[2]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5da5b412-7849-45d1-90a1-81155e581e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IGO74</value>
      <webElementGuid>ec36b3ad-6ab5-4475-a146-9cef7fbad67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainBody&quot;)/div[@class=&quot;pageContainer&quot;]/div[@class=&quot;flightPageContainer&quot;]/div[@class=&quot;flightPageSummaryMap&quot;]/div[1]/div[@class=&quot;flightPageSummaryContainer&quot;]/div[@class=&quot;flightPageFlightIdentifier&quot;]/div[@class=&quot;flightPageSummary&quot;]/div[@class=&quot;flightPageFriendlyIdent&quot;]/div[@class=&quot;flightPageIdentContainer&quot;]/div[@class=&quot;flightPageIdent&quot;]/h1[1]</value>
      <webElementGuid>b928a3d5-42ba-450a-8d96-e11c3a6acde9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainBody']/div/div[2]/div[3]/div/div/div/div[2]/div/div[2]/div/h1</value>
      <webElementGuid>32bdbcc3-9513-4411-b0aa-e06c0b145f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IndiGO 74'])[1]/following::h1[1]</value>
      <webElementGuid>3ef8f6f0-a6e2-4502-97c2-15d0cdac45df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/following::h1[2]</value>
      <webElementGuid>d9943527-422e-47ed-8bb1-e117fb6dcefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade account to see tail number'])[1]/preceding::h1[2]</value>
      <webElementGuid>a0f07a7f-4bd6-4576-bf7b-3981bc839c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IGO74']/parent::*</value>
      <webElementGuid>0c7a67cb-b383-46b7-b95c-5f6db05525e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h1</value>
      <webElementGuid>a644808e-517b-4637-a6c9-f5707f601d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'IGO74' or . = 'IGO74')]</value>
      <webElementGuid>79246118-b954-4a63-902c-652861907847</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
